import os
from dotenv import load_dotenv
load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

BTC_ONLY = os.getenv("BTC_ONLY", "true").lower() == "true"

COINS = ["BTC/USDT"] if BTC_ONLY else [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "XRP/USDT",
    "DOGE/USDT", "ADA/USDT", "AVAX/USDT", "LINK/USDT", "TON/USDT"
]

TIMEFRAME = "15m"
TIMEFRAME_4H = "4h"
CANDLES_NEEDED = 300
SCAN_INTERVAL_SECONDS = 900

STRONG_SIGNAL_THRESHOLD = 80
WEAK_SIGNAL_THRESHOLD = 58

# Long settings
TP_LONG_PERCENT = 1.8
SL_LONG_PERCENT = 1.0
TRAIL_ACTIVATE_LONG = 0.8
TRAILING_STOP_PERCENT = 0.4
MAX_HOLD_CANDLES_LONG = 32  # 8 hours

# Short settings (asymmetric - tighter)
TP_SHORT_PERCENT = 1.5
SL_SHORT_PERCENT = 0.9
TRAIL_ACTIVATE_SHORT = 0.7
MAX_HOLD_CANDLES_SHORT = 24  # 6 hours

# Legacy (for backward compatibility)
TP_PERCENT = 0.7
SL_PERCENT = 1.0
MAX_HOLD_CANDLES = 32
FEE_PERCENT = 0.05
PARTIAL_TP_PERCENT = 0.5
PARTIAL_TP_SIZE = 0.5
TRAILING_STOP_PERCENT = 0.5

LEVERAGE = int(os.getenv("LEVERAGE", "2"))

SIMULATION_MODE = True

HISTORIC_MODE = os.getenv("HISTORIC_MODE", "false").lower() == "true"
LIVE_MODE = os.getenv("LIVE_MODE", "false").lower() == "true"
HYBRID_MODE = os.getenv("HYBRID_MODE", "false").lower() == "true"

HISTORICAL_DAYS = int(os.getenv("HISTORICAL_DAYS", "90"))
BUY_AMOUNT = float(os.getenv("BUY_AMOUNT", "50"))

DAILY_TRADE_CAP = 999
SIGNAL_COOLDOWN_HOURS = 1.0
TRADE_HOURS_START = 7   # 07:00 UTC
TRADE_HOURS_END = 22    # 22:00 UTC
NEUTRAL_ZONE_PCT = 0.5  # Sleep if within 0.5% of EMA200
TRADE_HOURS_PREFERRED_START = 16
TRADE_HOURS_PREFERRED_END = 20
TRADE_DAYS_BLOCKED = [0, 5]  # Monday=0, Saturday=5
TRADE_HOURS_BLACKOUT_START = 4
TRADE_HOURS_BLACKOUT_END = 8
MAX_CONCURRENT_TRADES = 2
DAILY_LOSS_CAP = 2
CONSECUTIVE_SL_STOP = 3
MAX_NOTIONAL = 100.0

SL_OVERRIDES = {
    "DOGE/USDT": 0.8,
    "SOL/USDT": 0.7,
    "AVAX/USDT": 0.7,
    "LINK/USDT": 0.6
}